version: '3.8'

services:
  app:
    container_name: dalum-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SERVER_IP: ${EC2_PUBLIC_IP}

      DB_URL: ${DB_URL}
      DB_USER: ${POSTGRES_USER}
      DB_PW: ${POSTGRES_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}

    networks:
      - dalum-network

  db:
    container_name: dalum-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dalum-network

  redis:
    container_name: dalum-redis
    image: redis:alpine
    restart: always
    networks:
      - dalum-network

networks:
  dalum-network:
    driver: bridge